<a href="https://colab.research.google.com/github/CesarAugusto316/deep-learning/blob/main/vector_transpose.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
# import seaborn as sns

## Tansposing a vector

In [32]:
# vector
v1 = np.array([[1,2,3,4]])  # row vector
print(v1)

print(v1.T)

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [9]:
# matrix with numpy
m1 = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
print(m1)
print(m1.T)

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [12]:
# matrix with pytorch
m2 = torch.tensor([
    [1,2,3,4],
    [5,6,7,8]
])
print(m2)
print(m2.T)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])


In [23]:
v1 = np.array([
    [1,2,3,4]
])
v2 = np.array([
    [5,6,7,8]
])
print(v1)
print(v2)

dp1 = np.dot(v1, v2.T)
print(dp1)
print(np.sum(v1))
dp2 = np.sum(v1 * v2)
print(dp2)

[[1 2 3 4]]
[[5 6 7 8]]
[[70]]
10
70


In [28]:
v1 = torch.tensor(
    [1,2,3,4]
)
v2 = torch.tensor(
    [5,6,7,8]
)
print(v1)
print(v2)

dp1 = torch.dot(v1, v2)
print(dp1)
print(torch.sum(v1))
dp2 = torch.sum(v1 * v2)
print(dp2)

tensor([1, 2, 3, 4])
tensor([5, 6, 7, 8])
tensor(70)
tensor(10)
tensor(70)


In [30]:
v1_1d = np.array([1, 2, 3, 4])
v2_1d = np.array([5, 6, 7, 8])
print(v1_1d)
print(v2_1d)
np.dot(v1_1d, v2_1d)

[1 2 3 4]
[5 6 7 8]


70

In [36]:
t =torch.tensor([1, 2, 3, 4])
print(t)
print(t.T)

tensor([1, 2, 3, 4])
tensor([1, 2, 3, 4])
